version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: building file
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#      - store_test_results:
#          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apk_folder

      - run:
          name: Upload to Slack
          command: |
            curl -F file=@app/build/outputs/apk/production/debug/app-debug.apk -F "initial_comment=export latest debug apk" -F channels=sumyattesting -F token=$TOKEN -F title="production app" https://slack.com/api/files.upload
